---
title: "Darwin Core mapping"
subtitle: "For: camALIEN"
author:
- Sanne Govaert
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
    number_sections: yes
    toc: yes
    toc_depth: 3
    toc_float: yes
---

This script prepares data for publication on [GBIF](https://www.gbif.org/). The script transforms the raw data to a [Darwin Core Archive](https://www.gbif.org/darwin-core) that can be harvested by GBIF. It was developed for the [Biodiversa+ pilot on invasive alien species monitoring](https://www.biodiversa.eu/2024/02/02/pilot-on-invasive-alien-species-monitoring-first-year-report/) project.

# Setup 

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

## Load libraries

```{r}
library(here)
library(DBI)
library(duckdb)
library(dplyr)
library(readr)
```

## Load snapshot provided by Aarhus university

```{r}
file_location <- here::here("data", "raw", "detectionsummary_belgium_20250310_sample.csv")
snapshot <- readr::read_csv(file_location, show_col_types = FALSE) %>% 
  mutate(
    imagetype = "tiff"
    )
```


# Create dwc

# Create occurrence

```{r}
occurrence <-
  snapshot %>% 
  dplyr::mutate(
      .keep = "none",
      type = "Image",
      license = "CC0-1.0",
      rightsHolder = partner,
      datasetID = "",
      collectionCode = "camALIEN",
      datasetName = dataset_name,
      basisOfRecord = "MachineObservation",,
      occurrenceID = .data$detectionsummaryid,
      occurrenceStatus = "present",
      eventID = .data$imagedataid,
      #parentEventID = .data$deploymentID,
      eventDate = format(.data$timestamp, format = "%Y-%m-%dT%H:%M:%SZ"),
      habitat = "riverine habitats",
      samplingProtocol = "moving camera on vehicle",
      # samplingEffort = paste(
      #   format(.data$deploymentStart
      
      #, format = "%Y-%m-%dT%H:%M:%SZ"),
      #   format(.data$deploymentEnd, format = "%Y-%m-%dT%H:%M:%SZ"),
      #   sep = "/"
      # ),
      #eventRemarks = "x",
      minimumDistanceAboveSurfaceInMeters = camera_height,
      maximumDistanceAboveSurfaceInMeters = camera_height,
      decimalLatitude = .data$latitude,
      decimalLongitude = .data$longitude,
      geodeticDatum = "EPSG:4326", # WGS84
      #coordinateUncertaintyInMeters = .data$coordinateUncertainty,
      dateIdentified = format(
        .data$classificationTimestamp,
        format = "%Y-%m-%dT%H:%M:%SZ"
      ),
      identificationRemarks = paste0(
        # E.g. "classified by a machine with 89% certainty"
        dplyr::if_else(
          is.na(.data$classificationMethod),
          "classified",
          paste0("classified by a ", .data$classificationMethod)
        ),
        dplyr::if_else(
          is.na(.data$classificationProbability),
          "",
          paste0(" with ", .data$classificationProbability * 100, "% certainty")
        )
      ),
      taxonID = paste0("https://www.gbif.org/species/", .data$taxonID),
      scientificName = .data$scientificName,
      kingdom = "Plantae"
  )
    # ) %>%
    # dplyr::select(
    #   "type", "license", "rightsHolder", "datasetID", "collectionCode",
    #   "datasetName", "basisOfRecord", "dataGeneralizations", "occurrenceID",
    #   "individualCount", "sex", "lifeStage", "behavior", "occurrenceStatus",
    #   "occurrenceRemarks", "organismID", "eventID", "parentEventID",
    #   "eventDate", "habitat", "samplingProtocol", "samplingEffort",
    #   "eventRemarks", "locationID", "locality", "minimumDepthInMeters",
    #   "maximumDepthInMeters", "minimumDistanceAboveSurfaceInMeters",
    #   "maximumDistanceAboveSurfaceInMeters", "decimalLatitude",
    #   "decimalLongitude", "geodeticDatum", "coordinateUncertaintyInMeters",
    #   "coordinatePrecision", "identifiedBy", "dateIdentified",
    #   "identificationRemarks", "taxonID", "scientificName", "kingdom"
    # )
```


```{r}
  # Create Audubon/Audiovisual Media Description extension
  multimedia <-
    snapshot %>%
    dplyr::arrange(.data$deploymentID, .data$timestamp, .data$fileName) %>%
    dplyr::mutate(
      .keep = "none",
      occurrenceID = .data$observationID,
      identifier = .data$mediaID,
      `dc:type` = dplyr::case_when(
        grepl("video", .data$fileMediatype) ~ "MovingImage",
        .default = "StillImage"
      ),
      comments = dplyr::case_when(
        !is.na(favorite) & !is.na(mediaComments) ~
          paste("marked as favorite", mediaComments, sep = " | "),
        !is.na(favorite) ~ "marked as favorite",
        .default = .data$mediaComments
      ),
      `dcterms:rights` = media_license,
      CreateDate = format(.data$timestamp, format = "%Y-%m-%dT%H:%M:%SZ"),
      captureDevice = .data$cameraModel,
      resourceCreationTechnique = dplyr::recode(
        .data$captureMethod,
        "activityDetection" = "activity detection",
        "timeLapse" = "time lapse"
      ),
      accessURI = .data$filePath,
      `dc:format` = .data$fileMediatype,
      serviceExpectation = dplyr::if_else(
        as.logical(.data$filePublic),
        "online",
        "authenticate"
      )
    ) %>%
    dplyr::select(
      "occurrenceID", "identifier", "dc:type", "comments", "dcterms:rights",
      "CreateDate", "captureDevice", "resourceCreationTechnique", "accessURI",
      "dc:format", "serviceExpectation",
    )
```


